extends RefCounted

const AgentRuntimeScript = preload("res://scripts/ai_agent/agent_runtime.gd")
const MarketScript = preload("res://scripts/systems/market_system.gd")
const NpcEconomyScript = preload("res://scripts/systems/npc_economy_system.gd")
const SeasonScript = preload("res://scripts/systems/season_system.gd")
const GameDataScript = preload("res://scripts/core/game_data.gd")
const DialogueScene = preload("res://scenes/ui/dialogue_ui.tscn")


func run(assertions: TestAssert, tree: SceneTree) -> void:
	var disabled_config_path := "user://agent-main-integration-disabled.json"
	var disabled_config := FileAccess.open(disabled_config_path, FileAccess.WRITE)
	disabled_config.store_string(JSON.stringify({
		"enabled": false, "service_url": "", "token": "", "timeout_seconds": 10,
	}))
	disabled_config.close()
	var market := MarketScript.new()
	var economy := NpcEconomyScript.new()
	var season := SeasonScript.new()
	var runtime := AgentRuntimeScript.new()
	tree.root.add_child(market)
	tree.root.add_child(economy)
	tree.root.add_child(season)
	tree.root.add_child(runtime)
	market.configure(GameDataScript.get_market_items())
	economy.configure(market, GameDataScript.get_npc_economy_profiles(), GameDataScript.get_population_demand_profiles())
	assertions.truthy(runtime.configure(economy, market, season, null, disabled_config_path), "Agent runtime configures against authoritative systems")
	assertions.truthy(not runtime.service_enabled, "disabled client configuration keeps remote decisions off")
	assertions.truthy(economy.is_agent_managed("lao_li"), "merchant is removed from deterministic autonomy")
	assertions.truthy(economy.is_agent_managed("xuezhe_lin"), "explorer is removed from deterministic autonomy")
	assertions.truthy(economy.is_agent_managed("farmer_ahe"), "farmer is Agent managed")
	assertions.equal(runtime.farm_registry.get_plot("farmer_ahe", 11).plot_index, 11, "runtime creates twelve headless farmer plots")
	var saved: Dictionary = runtime.to_dict()
	var restored := AgentRuntimeScript.new()
	tree.root.add_child(restored)
	assertions.truthy(restored.configure(economy, market, season, null, disabled_config_path), "second runtime configures")
	assertions.truthy(restored.from_dict(saved), "Agent world state restores")
	assertions.equal(restored.to_dict(), saved, "Agent world state round trip is stable")
	var save_manager = tree.root.get_node("SaveManager")
	assertions.truthy(save_manager.configure_agent_runtime(runtime), "SaveManager accepts Agent runtime")
	assertions.truthy(runtime.configure_save_manager(save_manager), "runtime coordinates asynchronous memory sidecars")
	assertions.equal(save_manager.call("_gather_save_data").agent_world, runtime.to_dict(), "SaveManager gathers Agent world state")
	assertions.truthy(runtime.gateway.has_method("export_checkpoint"), "gateway exports memory checkpoints")
	assertions.truthy(runtime.gateway.has_method("import_checkpoint"), "gateway imports memory checkpoints")
	var dialogue = DialogueScene.instantiate()
	assertions.truthy(dialogue.has_method("start_agent_dialogue"), "Dialogue UI exposes AI speech entry")
	dialogue.free()
	restored.free()
	runtime.free()
	season.free()
	economy.free()
	market.free()
	DirAccess.remove_absolute(ProjectSettings.globalize_path(disabled_config_path))
